-- AlterTable
ALTER TABLE `SpecialCard` ADD COLUMN `roundProb1` INTEGER NULL DEFAULT 0,
    ADD COLUMN `roundProb2` INTEGER NULL DEFAULT 0,
    ADD COLUMN `roundProb3` INTEGER NULL DEFAULT 0,
    ADD COLUMN `roundProb4` INTEGER NULL DEFAULT 0,
    ADD COLUMN `roundProb5` INTEGER NULL DEFAULT 0;
