version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:balatroDev2024!@db:3306/balatro_online
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: balatroDev2024!
      MYSQL_DATABASE: balatro_online
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db_data:
  uploads_data: 