-- AlterTable
ALTER TABLE `SpecialCard` ADD COLUMN `conditionNumeric3` INTEGER NULL,
    ADD COLUMN `conditionNumeric4` INTEGER NULL,
    ADD COLUMN `conditionNumeric5` INTEGER NULL,
    ADD COLUMN `conditionOperator3` VARCHAR(191) NULL,
    ADD COLUMN `conditionOperator4` VARCHAR(191) NULL,
    ADD COLUMN `conditionOperator5` VARCHAR(191) NULL,
    ADD COLUMN `conditionType3` VARCHAR(191) NULL,
    ADD COLUMN `conditionType4` VARCHAR(191) NULL,
    ADD COLUMN `conditionType5` VARCHAR(191) NULL,
    ADD COLUMN `conditionValue3` VARCHAR(191) NULL,
    ADD COLUMN `conditionValue4` VARCHAR(191) NULL,
    ADD COLUMN `conditionValue5` VARCHAR(191) NULL,
    ADD COLUMN `effectTarget3` VARCHAR(191) NULL,
    ADD COLUMN `effectTarget4` VARCHAR(191) NULL,
    ADD COLUMN `effectTarget5` VARCHAR(191) NULL,
    ADD COLUMN `effectTiming3` VARCHAR(191) NULL,
    ADD COLUMN `effectTiming4` VARCHAR(191) NULL,
    ADD COLUMN `effectTiming5` VARCHAR(191) NULL,
    ADD COLUMN `effectType3` VARCHAR(191) NULL,
    ADD COLUMN `effectType4` VARCHAR(191) NULL,
    ADD COLUMN `effectType5` VARCHAR(191) NULL,
    ADD COLUMN `effectValue3` DOUBLE NULL,
    ADD COLUMN `effectValue4` DOUBLE NULL,
    ADD COLUMN `effectValue5` DOUBLE NULL;
